### ISSUE TITLE
想请教一些关于bpi-M2Z的问题

### ISSUE THREAD

**Issue by niguang1** [weimingtom/buildroot_bpi-m2z_hello#1]

**Comment by niguang1** [comment]
我入手这板子的目的和您一样，也是想研究一下buildroot相关的内容，但是一直走不通第一步。已经编过了官方的rootfs，uboot，kernel，但是不知道怎么生成image镜像，老哥有什么参考资料可以帮帮我吗？感激不尽。

**Comment by weimingtom** [comment]
buildroot资料和使用说明很少，只能靠自己摸索，buildroot的好处是方便生成镜像（类似buildroot编译img树莓派镜像，你可以搜索相关的资料，举一反三），然后烧录到tf卡，这样相当于交叉编译，但缺点是如果频繁编译和烧录会很烦人。最傻瓜的做法是用官方的镜像开发（也类似于树莓派），我只挖了坑，现在已经不研究buildroot了，放弃硬件方面，转向研究可移植的纯算法代码，而且只研究PC的linux环境，或者研究非linux的单片机，我认为研究嵌入式linux不如用虚拟机linux方便

**Comment by niguang1** [comment]
路漫漫其修远兮，我自己瞎玩吧，多谢前辈。
